language: python

python:
    - "3.7"

install: pip install -r requirements/development.txt

script:
    - radon cc statprly -nb --total-average
    - cat requirements/production.txt | safety check --stdin
    - isort -rc statprly tests --diff
    - pylint statprly
    - mypy statprly

after_success:
  - coverage report -m && coverage xml
  - bash <(curl -s https://codecov.io/bash)
