language: python

python:
    - "3.7"

install: pip install -r requirements/development.txt

script:
    - radon cc statprly -nb --total-average
    - cat requirements/production.txt | safety check --stdin
    - flake8 statprly && flake8 tests
    - isort statprly tests --diff
    - coverage run --include=statprly/* -m pytest -ra

after_success:
  - coverage report -m && coverage xml
  - bash <(curl -s https://codecov.io/bash)
